# Generated by Django 3.2.12 on 2022-02-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20220211_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='title',
        ),
    ]
